export const projects =[
    {
        id :'1',
        name:'Portfolio',
        short_description:'Create Portfolio using HTML5 & CSS3',
        long_description:'Building a simple personal portfolio using HTML5 & CSS3',
        image:require("../../assets/project/portfolio.png"),
        link:'https://github.com/MohammadAlnuqeiti/Portfolio',
        tools:'1,2',
    },
    {
        id :'2',
        name:'O-Trainers',
        short_description:'Attendance tracking system using JavaScript.',
        long_description:'a responsive and dynamic Attendance Tracker System that requires the user to register and sign in to see the data.',
        image:require("../../assets/project/o-trainers.png"),
        link:'https://github.com/MohammadAlnuqeiti/O-Trainers',
        tools:'1,2,3',
    },
    {
        id :'3',
        name:'Chanel for perfume',
        short_description:'E-commerce website for selling perfumes.',
        long_description:'E-commerce website using WordPress The user can add product to carts and make payment.',
        image:require("../../assets/project/wordbress.png"),
        link:'https://github.com/MohammadAlnuqeiti/WordPress_Ecommerce_website',
        tools:'8',
    },
    {
        id :'4',
        name:'BrightEyes',
        short_description:'E-commerce web application using PHP and MYSQL.',
        long_description:'E-commerce web application using PHP and MYSQL.',
        image:require("../../assets/project/brighteyes.png"),
        link:'https://github.com/MohammadAlnuqeiti/BrightEyes',
        tools:'5,7',
    },
    {
        id :'5',
        name:'YourTour',
        short_description:'Flight reservation system using Laravel.',
        long_description:'YourTour is a tour booking system where We provide offers on the site for tourist trips that are updated continuously, the user can book one of the available trips, and the date of reservation starts after 3 days from the current date, the user can delete and modify the reservation.Along with an admin dashboard to manage the system seamlessly.',
        image:require("../../assets/project/yourtour.png"),
        link:'https://github.com/MohammadAlnuqeiti/YourTour',
        tools:'6,7',
    },
    {
        id :'6',
        name:'WE SHARE',
        short_description:'Social media platform using REACT.',
        long_description:'Social media using the React-JS, PHP and MySQL that allows users to post, comment, and like to friends.',
        image:require("../../assets/project/we-share.png"),
        link:'https://github.com/MohammadAlnuqeiti/WE_SHARE',
        tools:'4,5',
    },
    {
        id :'7',
        name:'Nuqeiti Training',
        short_description:'A platform that provides distance learning courses using Laravel.',
        long_description:'The nuqeiti training project is an initiative providing educational resources remotely, empowering learners from all governorate to pursue their education at their convenience. It offers a diverse range of courses spanning different subjects and levels of difficulty.',
        image:require("../../assets/project/nuqeiti-training.png"),
        link:'https://github.com/MohammadAlnuqeiti/Nuqeiti_Training',
        tools:'6,7',
    },
    {
        id :'8',
        name:'Productive Kitchen',
        short_description:'A site for production kitchens in the city of Aqaba.',
        long_description:'website that connect customers with junoir cheifs who provide some qualityfood products throught the website.',
        image:require("../../assets/project/productive-kitchen.png"),
        link:'https://github.com/MohammadAlnuqeiti/Productive_Kitchen',
        tools:'6,7',
    },
]
export const tools =[
    {
        id:'1',
        name:'HTML',
        color:'#e44d26',
        description:'HTML.',
        image:require("../../assets/project/HTML.png"),
    },
    {
        id:'2',
        name:'CSS',
        color:'#214ce5',
        description:'CSS',
        image:require("../../assets/project/CSS.png"),
    },
    {
        id:'3',
        name:'JAVASCRIPT',
        color:'#efd81d',
        description:'javascript javascript javascript',
        image:require("../../assets/project/JAVASCRIPT.png"),
    },
    {
        id:'4',
        name:'REACT',
        color:'#087ea4',
        description:'REACT',
        image:require("../../assets/project/react.png"),
    },
    {
        id:'5',
        name:'PHP',
        color:'#787cb4',
        description:'PHP',
        image:require("../../assets/project/php.png"),
    },
    {
        id:'6',
        name:'LARAVEL',
        color:'#ef3b2d',
        description:'LARAVEL',
        image:require("../../assets/project/LARAVEL.png"),
    },
    {
        id:'7',
        name:'MySQL',
        color:'#00618a',
        description:'MySQL',
        image:require("../../assets/project/MySQL.png"),
    },
    {
        id:'8',
        name:'WordPress',
        color:'#32373c',
        description:'WordPress',
        image:require("../../assets/project/WordPress.png"),
    },
]